"""
Dump Claude Code session transcripts for this project into TRANSCRIPT.md.

Run it yourself:  uv run python dump_transcript.py

It scans ~/.claude/projects/ for sessions whose recorded working directory is
this repo, so it picks up every session you did here, including ones from
another machine of yours once you have pulled them.

Claude runs this at each part checkpoint and before you submit. After writing,
the file is committed by itself ("Update TRANSCRIPT.md"), so the record is
always in the history; you never have to remember it.

TRANSCRIPT.md is merged, not rebuilt: sessions found locally are regenerated;
sections for sessions only present in the existing file (e.g., committed from
another machine of yours) are preserved.

What is recorded: everything you typed and everything Claude said, plus
one-line summaries of tool calls. What is omitted: tool output and Claude's
internal reasoning (both bulky and reproducible from the code itself).

Cross-platform notes: all file I/O is explicit UTF-8 with "\n" newlines, and
no shell features are used, so this works identically on macOS, Linux, and
native Windows.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
OUTPUT = REPO_ROOT / "TRANSCRIPT.md"

FILE_HEADER = """\
# Session transcript (auto-generated)

Generated by `dump_transcript.py` — do not edit by hand; edits will be
overwritten. Tool outputs and model reasoning are omitted; tool calls are
summarized as one-liners.
"""

SECTION_RE = re.compile(
    r"<!-- transcript-session: (?P<id>[\w-]+) \| (?P<ts>\S+) -->\n"
    r"(?P<body>.*?)"
    r"<!-- end-session: (?P=id) -->\n",
    re.DOTALL,
)

SYSTEM_REMINDER_RE = re.compile(r"<system-reminder>.*?</system-reminder>", re.DOTALL)
COMMAND_RE = re.compile(r"<command-name>(.*?)</command-name>", re.DOTALL)


def tool_one_liner(block: dict) -> str:
    """Render a tool_use content block as a single readable line."""
    name = block.get("name", "tool")
    inp = block.get("input") or {}
    if name == "Bash":
        brief = inp.get("description") or inp.get("command", "")
    elif name in ("Read", "Edit", "Write", "NotebookEdit"):
        brief = inp.get("file_path", "")
    elif name == "Agent":
        brief = inp.get("description", "")
    elif name == "Skill":
        brief = inp.get("skill", "")
    else:
        brief = json.dumps(inp, ensure_ascii=False)
    brief = " ".join(str(brief).split())
    if len(brief) > 100:
        brief = brief[:97] + "..."
    return f"- 🔧 `{name}` — {brief}" if brief else f"- 🔧 `{name}`"


def clean_user_text(text: str) -> str:
    """Strip harness-injected noise from user message text."""
    text = SYSTEM_REMINDER_RE.sub("", text)
    m = COMMAND_RE.search(text)
    if m:
        return f"*(ran `{m.group(1).strip()}`)*"
    return text.strip()


def render_session(path: Path) -> tuple[str, str, str] | None:
    """Parse one session JSONL. Returns (session_id, start_ts, markdown) or None."""
    session_id = path.stem
    start_ts = None
    chunks: list[tuple[str, str]] = []  # (speaker, markdown chunk)

    with open(path, encoding="utf-8") as f:
        for line in f:
            try:
                e = json.loads(line)
            except json.JSONDecodeError:
                continue
            if e.get("type") not in ("user", "assistant"):
                continue
            if e.get("isSidechain") or e.get("isMeta") or e.get("isApiErrorMessage"):
                continue
            msg = e.get("message")
            if not isinstance(msg, dict):
                continue
            if start_ts is None:
                start_ts = e.get("timestamp", "")

            content = msg.get("content")
            parts: list[str] = []
            if e["type"] == "user":
                if isinstance(content, str):
                    parts.append(clean_user_text(content))
                elif isinstance(content, list):
                    for b in content:
                        if isinstance(b, dict) and b.get("type") == "text":
                            parts.append(clean_user_text(b.get("text", "")))
                speaker = "User"
            else:
                if isinstance(content, list):
                    for b in content:
                        if not isinstance(b, dict):
                            continue
                        if b.get("type") == "text":
                            parts.append(b.get("text", "").strip())
                        elif b.get("type") == "tool_use":
                            parts.append(tool_one_liner(b))
                speaker = "Claude"

            text = "\n\n".join(p for p in parts if p)
            if text:
                chunks.append((speaker, text))

    if not chunks:
        return None

    # Coalesce consecutive chunks from the same speaker.
    lines = []
    prev_speaker = None
    for speaker, text in chunks:
        if speaker != prev_speaker:
            lines.append(f"\n**{speaker}:**\n")
            prev_speaker = speaker
        lines.append(text + "\n")

    ts = start_ts or ""
    date = ts[:19].replace("T", " ") if ts else "unknown time"
    n_user = sum(1 for s, _ in chunks if s == "User")
    body = (
        f"## Session `{session_id[:8]}` — {date}\n\n"
        f"*{n_user} user turns. Tool outputs and reasoning omitted.*\n"
        + "".join(lines)
        + "\n"
    )
    return session_id, ts, body


def sessions_from_scan() -> list[Path]:
    """Find the sessions whose recorded cwd is this repo."""
    import os

    # ~/.claude is where Claude Code keeps its session store, unless CLAUDE_CONFIG_DIR
    # says otherwise. It is unset on a normal laptop.
    config = Path(os.environ.get("CLAUDE_CONFIG_DIR") or (Path.home() / ".claude"))
    projects = config / "projects"
    here = os.path.normcase(str(REPO_ROOT))
    found = []
    if not projects.is_dir():
        return found
    for f in projects.glob("*/*.jsonl"):
        try:
            with open(f, encoding="utf-8") as fh:
                for line in fh:
                    try:
                        e = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    cwd = e.get("cwd")
                    if cwd:
                        if os.path.normcase(str(Path(cwd).resolve())) == here:
                            found.append(f)
                        break
        except OSError:
            continue
    return sorted(found)


def current_session(session_files: list[Path]) -> str | None:
    """Which session is the one running now: the most recently written file."""
    if session_files:
        return max(session_files, key=lambda f: f.stat().st_mtime).stem
    return None


def main():
    session_files = sessions_from_scan()
    now = current_session(session_files)

    # Start from sections already in TRANSCRIPT.md (preserves sessions we
    # can't see locally, e.g. ones committed from another machine).
    sections: dict[str, tuple[str, str]] = {}
    if OUTPUT.exists():
        existing = OUTPUT.read_text(encoding="utf-8")
        for m in SECTION_RE.finditer(existing):
            sections[m.group("id")] = (m.group("ts"), m.group("body"))

    for f in session_files:
        rendered = render_session(f)
        if rendered:
            sid, ts, body = rendered
            sections[sid] = (ts, body)

    if not sections:
        print("No sessions found for this project; TRANSCRIPT.md not written.")
        print("0 sessions found; this session is not in TRANSCRIPT.md.")
        return

    out = [FILE_HEADER]
    for sid, (ts, body) in sorted(sections.items(), key=lambda kv: kv[1][0]):
        out.append(f"\n<!-- transcript-session: {sid} | {ts or 'unknown'} -->\n")
        out.append(body)
        out.append(f"<!-- end-session: {sid} -->\n")
    text = "".join(out)

    unchanged = OUTPUT.exists() and OUTPUT.read_text(encoding="utf-8") == text
    if not unchanged:  # skip the write when nothing moved, to avoid mtime churn
        with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"Wrote {OUTPUT.name}: {len(sections)} session(s).")
        auto_commit()

    # The checkpoint skill reads this line: it is how the student sees that the session they
    # are in right now is in the file they are about to commit.
    here = "yes" if now and now in sections else "no"
    print(f"{len(sections)} session(s) found; this session in TRANSCRIPT.md: {here}.")


def auto_commit() -> None:
    """Commit TRANSCRIPT.md by itself, so the record is never left uncommitted. Quiet on any
    failure (no git, no identity, a merge in progress): the file is still written."""
    import subprocess

    def git(*args):
        return subprocess.run(["git", *args], cwd=REPO_ROOT, capture_output=True, text=True)

    if git("rev-parse", "--is-inside-work-tree").stdout.strip() != "true":
        return
    if (REPO_ROOT / ".git" / "MERGE_HEAD").exists():
        return
    if not git("config", "user.name").stdout.strip() or not git("config", "user.email").stdout.strip():
        return
    if git("add", "--", OUTPUT.name).returncode != 0:
        return
    if not git("diff", "--cached", "--quiet", "--", OUTPUT.name).returncode:
        return  # nothing staged for it
    git("commit", "-q", "-m", "Update TRANSCRIPT.md", "--", OUTPUT.name)


if __name__ == "__main__":
    main()
